# Production Docker Compose
# Usage: docker compose -f docker-compose.prod.yml up --build

services:
  postgres:
    image: postgres:15
    container_name: hotel_postgres_prod
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: hotel_redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis_prod_data:/data
    restart: unless-stopped
    env_file:
      - .env.prod

  app:
    build:
      context: .
      target: production
    container_name: hotel_app_prod
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.prod
    environment:
      NODE_ENV: prod
    restart: unless-stopped

volumes:
  postgres_prod_data:
  redis_prod_data:
