services:
  postgres:
    image: postgres:15
    container_name: hotel_postgres
    env_file:
      - .env.${NODE_ENV}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: hotel_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always
    env_file:
      - .env.${NODE_ENV}
  app:
    build: .
    container_name: hotel_app
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.${NODE_ENV} # <- This loads the right .env file
    environment:
      NODE_ENV: ${NODE_ENV} # <- Pass NODE_ENV into the container

volumes:
  postgres_data:
  redis_data:
