name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t mohamedsheriif/hotel-booking-api .
      - name: Push Docker image
        run: docker push mohamedsheriif/hotel-booking-api:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from Docker Hub
        run: docker pull mohamedsheriif/hotel-booking-api:latest
      - name: Stop and remove container
        run: docker stop hotel-booking-api && docker rm hotel-booking-api
      - name: Run container
        run: docker run -d -p 3000:3000 --name hotel-booking-api  mohamedsheriif/hotel-booking-api:latest
